### ISSUE TITLE
Partnership with Yandex.Rabota

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/rubyjobs.dev#1]
https://yandex.ru/support/rabota/partners/requirements.html

**Comment by JuPlutonic** [comment]
Вижу отличную возможность реализовать это через гем rabl!
Шаблон yandex_rabota.rabl на много проще будет написать, чем громозкие инструкции XSLT-процессору.
https://github.com/nesquena/rabl
https://github.com/nesquena/rabl/wiki/Setup-for-Sinatra (нужны гемы: builder и два activesupport-а).

**Comment by davydovanton** [comment]
зависимость от activesupport не подходит, нужно найти что-то другое или писать самому

**Comment by davydovanton** [comment]
спасибо!

**Comment by VMashanov** [comment]
Яндекс.Работа всё.
Ишью можно закрывать.

**Comment by davydovanton** [comment]
грустно. спасибо что написал!
