### ISSUE TITLE
Filters for list of vacancies

### ISSUE THREAD

**Issue by asusikov** [davydovanton/rubyjobs.dev#33]
## What

Add filters by type of vacancy and ability to remote work

## Why

It will be very handy to have ability to filter vacancies to get list with offers what you need

## How

Add select box with list of types and checkbox to filter remote vacancies on page with list of vacancies

**Comment by JuPlutonic** [comment]
Как раз можно поиграться с ханамишной MVC-кой
Please add Country / City / Relocation filter !!!!!

**Comment by davydovanton** [comment]
Привет, я сделал минимальный поиск. закрою ишю. теперь надо дизайн чуть краше сделать, но это уже в следующий раз
