### ISSUE TITLE
Different ruby version in Gemfile and CONTRIBUTING.md

### ISSUE THREAD

**Issue by avbabushkin** [davydovanton/rubyjobs.dev#67]
https://github.com/davydovanton/rubyjobs.dev/blob/36bed4c0cc419216e5d269c0a727c165fece230c/Gemfile#L5
https://github.com/davydovanton/rubyjobs.dev/blob/1575ddf26d9cee0f9362569a942421d86a620be9/CONTRIBUTING.md#L54

Which version of ruby should be used to contribute?

**Comment by davydovanton** [comment]
hey, thanks for the issue. The right version is `2.7.0`

**Comment by dmitriy-spivakov** [comment]
Hi @davydovanton , I've added a PR for this issue (#69), please take a look at it when you have time.

**Comment by davydovanton** [comment]
@dmitriy-spivakov hey, thanks for the PR. I think we can finally close the issue! ❤️
